### PR TITLE
Updates for release+containerization

### PR DESCRIPTION
**Pull request by mark-a-potts**
## Describe your changes  
Added *_release_* versions of scripts and templates to make the release more portable/machine agnostic

List any associated PRs  in the submodules.
This includes a PR to land-IMS_proc that was required to build the code.

The only change that might affect the current code is the change to letkfoi_snow.yaml, which was required to work with a newer version of JEDI.

## Issue ticket number and link
This is in preparation for the public release.

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)?

### CODE REVIEW

**Comment by ClaraDraper-NOAA** [comment]
Thanks @mark-a-potts. I'll do a detailed review later. However, the change to the yamls is going to be a problem. I suggest: within the yaml folder, create subfolders with the yamls specific to the jedi version. To date, I've been identifying the JEDI version using the date that I checked it out. Using this system, the current yamls can all go in a folder '20220921'.

**Comment by mark-a-potts** [comment]
I have now folded in environment variables to handle running with singularity. I also reverted the yaml file to the original state and put in some sed commands in the do_landDA_release.sh script to remove the problematic entries.  Hopefully, this will leave your original code untouched while adding capability to run using either singularity or on Hera or Orion.

**Comment by ClaraDraper-NOAA** [comment]
Thanks Mark. Is your intention for that the new scripts \*release\* replace the current ones? Should I be able to run on hera (without using containers) with the new scripts?

**Comment by ClaraDraper-NOAA** [comment]
Also, I'm having the same issue as for IMS_proc with the develop version. I googled it, and it seems that the default behaviour is for the git website to show the differences from the latest common commit, which is why I can't see my latest changes here. (from what I read this has been their policy for a while, so I'm confused as to why it's suddenly changed for me). Anyway, the solution is for you to update your branch with my latest develop commits (from Jan 20). Can you please merge these in? (and maybe check that all submodules are updated?)

**Comment by mark-a-potts** [comment]
The intent of the *release* scripts is to not break any current capabilities that you have. For the actual release, we will probably want to remove your original scripts or put them in a separate folder or something. 

What I am trying to do for the release is have users set up a consistent directory structure that has all the directories referenced by the application and the land-offline_workflow underneath.  So, it will look like this---

mpotts@Orion-login-1:/work/noaa/da/mpotts/land-release$ tree -L 1
.
├── [mpotts   4.0K]  C96
├── [mpotts   4.0K]  C96.mx100_frac
├── [mpotts   4.0K]  cycle_land
├── [mpotts   4.0K]  DA
├── [mpotts   4.0K]  ensemble_pert
├── [mpotts   4.0K]  forcing
├── [mpotts   4.0K]  land-offline_workflow
├── [mpotts   4.0K]  orog_files
├── [mpotts   4.0K]  single
├── [mpotts   4.0K]  static
├── [mpotts   4.0K]  v2t_data
└── [mpotts   4.0K]  workdir

Ultimately, the directories can all be links and the structure could be changed, but getting it in a consistent order will allow us to simplify the scripting and make it portable. 

I am making a few more tweaks to the scripts and then I'll send out some directions on how to test everything.

**Comment by ClaraDraper-NOAA** [comment]
@jswhit You might want to look at what mark is doing. I'm hoping to merge these changes in in the next day or so.

**Comment by ClaraDraper-NOAA** [comment]
> The intent of the _release_ scripts is to not break any current capabilities that you have. For the actual release, we will probably want to remove your original scripts or put them in a separate folder or something.
> 
> What I am trying to do for the release is have users set up a consistent directory structure that has all the directories referenced by the application and the land-offline_workflow underneath. So, it will look like this---
> 
> mpotts@Orion-login-1:/work/noaa/da/mpotts/land-release$ tree -L 1 . ├── [mpotts 4.0K] C96 ├── [mpotts 4.0K] C96.mx100_frac ├── [mpotts 4.0K] cycle_land ├── [mpotts 4.0K] DA ├── [mpotts 4.0K] ensemble_pert ├── [mpotts 4.0K] forcing ├── [mpotts 4.0K] land-offline_workflow ├── [mpotts 4.0K] orog_files ├── [mpotts 4.0K] single ├── [mpotts 4.0K] static ├── [mpotts 4.0K] v2t_data └── [mpotts 4.0K] workdir
> 
> Ultimately, the directories can all be links and the structure could be changed, but getting it in a consistent order will allow us to simplify the scripting and make it portable.
> 
> I am making a few more tweaks to the scripts and then I'll send out some directions on how to test everything.

@mark-a-potts As with the tarball of files, it would be faster for me to restructure the directories myself than to try to edit this ( I can also then update my document with the file list to include the directories that each file should go into). 

Also, this is a mix of directories containing code, input files, and output files. Can we create a second layer of directories to separate these (or at the very least, change the directory names to indicate which is which)? 

Going forward, I suggest that we close this PR. Then: 
1) I create a new develop, with some of the (unfinished) ensemble work removed. 
2) I create a branch of that develop to be used for your release that excludes the stuff that you don't need (IMS). 
3) You create a new PR into that branch. 

Let me know if you agree, and I'll get started.

**Comment by mark-a-potts** [comment]
I can close this PR and resubmit after you get the new develop in place. The structure of the directories can be configured however you would like, and I think that the data and the work directories can be separated. The sooner we have the new structure, the better, though. We need to get something consistent that we can write documentation about and develop testing for.

**Pull request closed without merging**
